import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ChartPage from "./user/ChartPage";
import dayjs from "dayjs";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="chart-container">
          {/* <ChartPage
            timeFor='Daily'
            dataCalculated={dailyData}
            labels={dailyLabels}
          />
          <ChartPage
            timeFor='Weekly'
            dataCalculated={weeklyData}
            labels={weeklyLabels}
          />
          <ChartPage
            timeFor='Monthly'
            dataCalculated={monthlyData}
            labels={monthlyLabels}
          />
          <ChartPage
            timeFor='Quarterly'
            dataCalculated={quarterlyData}
            labels={quarterlyLabels}
        /> */}
        </div>
      </main>
    </div>
  );
}
